"""initial schema (gradient baseline)

Squashed baseline for the Gradient fresh start. The 30 incremental mcat-coach
PoC migrations (0001_initial .. T95) plus the P0 T1/T2 churn were collapsed
into this single CREATE-everything revision, autogenerated from the current
SQLAlchemy models against an empty DB (SPEC §O: no PoC data migrated). It is
the only migration; `down_revision = None`.

Revision ID: 0001_initial
Revises:
Create Date: 2026-05-26

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anki_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope_kind', sa.Text(), nullable=False),
    sa.Column('scope_value', sa.Text(), nullable=False),
    sa.Column('scheduled_unlock_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_unlock_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('card_ids', postgresql.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('note_ids', postgresql.ARRAY(sa.BigInteger()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('max_cards', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Text(), server_default='most_specific_first', nullable=True),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('failure_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("scope_kind IN ('cc','topic')", name='ck_anki_assignments_scope_kind'),
    sa.CheckConstraint("status IN ('pending','unlocked','completed','skipped','failed')", name='ck_anki_assignments_status'),
    sa.CheckConstraint('max_cards IS NULL OR max_cards > 0', name='ck_anki_assignments_max_cards_pos'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_anki_assignments_actual_unlock', 'anki_assignments', ['actual_unlock_at'], unique=False)
    op.create_index('ix_anki_assignments_status_scheduled', 'anki_assignments', ['status', 'scheduled_unlock_at'], unique=False)
    op.create_table('anki_load_config',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('daily_card_review_budget', sa.Integer(), nullable=False),
    sa.Column('daily_minutes_budget', sa.Numeric(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('daily_card_review_budget > 0', name='ck_anki_load_config_budget_pos'),
    sa.CheckConstraint('daily_minutes_budget > 0', name='ck_anki_load_config_minutes_pos'),
    sa.CheckConstraint('id = 1', name='ck_anki_load_config_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anki_notes',
    sa.Column('note_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('deck_name', sa.Text(), nullable=True),
    sa.Column('model_name', sa.Text(), nullable=True),
    sa.Column('fields_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_table('anki_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('card_ids', postgresql.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('note_ids', postgresql.ARRAY(sa.BigInteger()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('deck_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('failure_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending','pushed','failed')", name='ck_anki_reviews_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_anki_reviews_status_date', 'anki_reviews', ['status', 'review_date'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('llm_batch_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anthropic_batch_id', sa.Text(), nullable=False),
    sa.Column('extractor', sa.Text(), nullable=False),
    sa.Column('extractor_version', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processing_status', sa.Text(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('succeeded_count', sa.Integer(), nullable=False),
    sa.Column('errored_count', sa.Integer(), nullable=False),
    sa.Column('canceled_count', sa.Integer(), nullable=False),
    sa.Column('expired_count', sa.Integer(), nullable=False),
    sa.Column('processing_count', sa.Integer(), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_cost_usd', sa.NUMERIC(precision=10, scale=4), nullable=True),
    sa.Column('result_persisted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anthropic_batch_id', name='uq_llm_batch_runs_anthropic_id')
    )
    op.create_index('ix_llm_batch_runs_extractor_submitted', 'llm_batch_runs', ['extractor', 'submitted_at'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_model', sa.Text(), nullable=True),
    sa.Column('described_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index('ix_media_undescribed', 'media', ['id'], unique=False, postgresql_where=sa.text('description IS NULL'))
    op.create_table('passages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uworld_passage_id', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('plain_text', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash', name='uq_passages_content_hash')
    )
    op.create_index('ix_passages_uworld_id', 'passages', ['uworld_passage_id'], unique=True, postgresql_where=sa.text('uworld_passage_id IS NOT NULL'))
    op.create_table('raw_captures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), server_default='uworld', nullable=False),
    sa.Column('qid', sa.Text(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_html', sa.Text(), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parse_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extension_version', sa.Text(), nullable=False),
    sa.Column('uworld_test_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('uworld')", name='ck_raw_captures_source'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_captures_captured_at', 'raw_captures', ['captured_at'], unique=False)
    op.create_index('ix_raw_captures_qid', 'raw_captures', ['qid'], unique=False)
    op.create_index('ix_raw_captures_qid_with_warnings', 'raw_captures', ['qid'], unique=False, postgresql_where=sa.text('parse_warnings IS NOT NULL'))
    op.create_table('task_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('running', 'succeeded', 'failed', name='task_run_status'), nullable=False),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.NUMERIC(precision=10, scale=4), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_runs_job_name'), 'task_runs', ['job_name'], unique=False)
    op.create_index('ix_task_runs_job_started', 'task_runs', ['job_name', 'started_at'], unique=False)
    op.create_table('anki_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anki_card_id', sa.BigInteger(), nullable=False),
    sa.Column('deck_name', sa.Text(), nullable=False),
    sa.Column('note_id', sa.BigInteger(), nullable=True),
    sa.Column('model_name', sa.Text(), nullable=True),
    sa.Column('fields_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('ease', sa.Integer(), nullable=True),
    sa.Column('lapses', sa.Integer(), nullable=True),
    sa.Column('queue', sa.Integer(), nullable=True),
    sa.Column('sync_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['anki_notes.note_id'], name='fk_anki_cards_note_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deck_name', 'anki_card_id', name='uq_anki_cards_deck_card')
    )
    op.create_index('ix_anki_cards_due_date', 'anki_cards', ['due_date'], unique=False)
    op.create_table('anki_writes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('payload_hash', sa.Text(), nullable=False),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('mcp','scheduler','manual','test')", name='ck_anki_writes_source'),
    sa.CheckConstraint("status IN ('succeeded','failed')", name='ck_anki_writes_status'),
    sa.ForeignKeyConstraint(['assignment_id'], ['anki_assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['anki_reviews.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_anki_writes_occurred_at', 'anki_writes', ['occurred_at'], unique=False)
    op.create_table('outline_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['outline_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'parent_id', 'name', name='uq_outline_nodes_course_parent_name')
    )
    op.create_index('ix_outline_nodes_course_id', 'outline_nodes', ['course_id'], unique=False)
    op.create_index('ix_outline_nodes_parent_id', 'outline_nodes', ['parent_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qid', sa.Text(), nullable=False),
    sa.Column('passage_id', sa.Integer(), nullable=True),
    sa.Column('stem_html', sa.Text(), nullable=False),
    sa.Column('stem_plain', sa.Text(), nullable=False),
    sa.Column('choices', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_choice', sa.Text(), nullable=False),
    sa.Column('explanation_html', sa.Text(), nullable=True),
    sa.Column('explanation_plain', sa.Text(), nullable=True),
    sa.Column('uworld_aamc_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('needs_categorization', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qid')
    )
    op.create_index('ix_questions_needs_categorization', 'questions', ['id'], unique=False, postgresql_where=sa.text('needs_categorization = true'))
    op.create_index('ix_questions_passage_id', 'questions', ['passage_id'], unique=False)
    op.create_table('anki_card_reviews',
    sa.Column('review_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ease', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('interval_before', sa.Integer(), nullable=True),
    sa.Column('interval_after', sa.Integer(), nullable=True),
    sa.Column('time_ms', sa.Integer(), nullable=True),
    sa.CheckConstraint("type IN ('learn', 'review', 'relearn', 'cram')", name='ck_anki_card_reviews_type'),
    sa.CheckConstraint('ease BETWEEN 1 AND 4', name='ck_anki_card_reviews_ease'),
    sa.ForeignKeyConstraint(['card_id'], ['anki_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index('ix_anki_card_reviews_card_reviewed', 'anki_card_reviews', ['card_id', 'reviewed_at'], unique=False)
    op.create_table('anki_note_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_raw', sa.Text(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('question_qid', sa.Text(), nullable=True),
    sa.Column('parsed_kind', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), server_default='schema_map', nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('extractor_version', sa.Text(), nullable=True),
    sa.Column('manual_review', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_overridden', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('overridden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(source = 'llm' AND confidence IS NOT NULL) OR (source <> 'llm' AND confidence IS NULL)", name='ck_anki_note_tags_confidence_when_llm'),
    sa.CheckConstraint("source IN ('schema_map', 'llm', 'manual')", name='ck_anki_note_tags_source'),
    sa.CheckConstraint('confidence IS NULL OR (confidence BETWEEN 0.0 AND 1.0)', name='ck_anki_note_tags_confidence_range'),
    sa.CheckConstraint('confidence IS NULL OR confidence >= 0.5 OR manual_review', name='ck_anki_note_tags_low_conf_flagged'),
    sa.ForeignKeyConstraint(['node_id'], ['outline_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['note_id'], ['anki_notes.note_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_id', 'node_id', 'source', name='uq_anki_note_tags_node_source'),
    sa.UniqueConstraint('note_id', 'tag_raw', name='uq_anki_note_tags_note_tag')
    )
    op.create_index('ix_anki_note_tags_node_id', 'anki_note_tags', ['node_id'], unique=False)
    op.create_index('ix_anki_note_tags_question_qid', 'anki_note_tags', ['question_qid'], unique=False)
    op.create_index('ix_anki_note_tags_source', 'anki_note_tags', ['source'], unique=False)
    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('selected_choice', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_seconds', sa.Integer(), nullable=True),
    sa.Column('flagged', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('uworld_test_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attempts_attempted_at', 'attempts', ['attempted_at'], unique=False)
    op.create_index('ix_attempts_question_attempted', 'attempts', ['question_id', 'attempted_at'], unique=False)
    op.create_index('ix_attempts_question_id', 'attempts', ['question_id'], unique=False)
    op.create_index('ix_attempts_uworld_test_id', 'attempts', ['uworld_test_id'], unique=False)
    op.create_table('question_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_format', sa.Text(), nullable=False),
    sa.Column('reasoning_type', sa.Text(), nullable=False),
    sa.Column('requires_calculation', sa.Boolean(), nullable=False),
    sa.Column('calculation_steps', sa.Integer(), server_default='0', nullable=False),
    sa.Column('involves_graph_or_figure', sa.Boolean(), nullable=False),
    sa.Column('involves_data_table', sa.Boolean(), nullable=False),
    sa.Column('has_negative_phrasing', sa.Boolean(), nullable=False),
    sa.Column('passage_length_bucket', sa.Text(), nullable=True),
    sa.Column('passage_type', sa.Text(), nullable=True),
    sa.Column('distractor_difficulty', sa.Text(), nullable=False),
    sa.Column('trap_distractor_present', sa.Boolean(), nullable=False),
    sa.Column('common_misconception', sa.Text(), nullable=True),
    sa.Column('jargon_density', sa.Text(), nullable=False),
    sa.Column('key_concept_summary', sa.Text(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extractor_version', sa.Text(), nullable=False),
    sa.CheckConstraint("distractor_difficulty IN ('low', 'medium', 'high')", name='ck_question_features_distractor_difficulty'),
    sa.CheckConstraint("jargon_density IN ('low', 'medium', 'high')", name='ck_question_features_jargon_density'),
    sa.CheckConstraint("passage_length_bucket IN ('short', 'medium', 'long') OR passage_length_bucket IS NULL", name='ck_question_features_passage_length_bucket'),
    sa.CheckConstraint("passage_type IN ('experimental', 'descriptive', 'hypothesis_driven') OR passage_type IS NULL", name='ck_question_features_passage_type'),
    sa.CheckConstraint("question_format IN ('discrete', 'passage_based')", name='ck_question_features_question_format'),
    sa.CheckConstraint("reasoning_type IN ('recall', 'comprehension', 'application', 'analysis', 'inference')", name='ck_question_features_reasoning_type'),
    sa.CheckConstraint('calculation_steps >= 0', name='ck_question_features_calculation_steps_nonneg'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_table('question_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('extractor_version', sa.Text(), nullable=True),
    sa.Column('manual_review', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_overridden', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('overridden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(source = 'llm' AND confidence IS NOT NULL) OR (source <> 'llm' AND confidence IS NULL)", name='ck_question_tags_confidence_when_llm'),
    sa.CheckConstraint("source IN ('schema_map', 'llm', 'manual')", name='ck_question_tags_source'),
    sa.CheckConstraint('confidence IS NULL OR (confidence BETWEEN 0.0 AND 1.0)', name='ck_question_tags_confidence_range'),
    sa.CheckConstraint('confidence IS NULL OR confidence >= 0.5 OR manual_review', name='ck_question_tags_low_conf_flagged'),
    sa.ForeignKeyConstraint(['node_id'], ['outline_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'node_id', 'source', name='uq_question_tags_node_source')
    )
    op.create_index('ix_question_tags_node_id', 'question_tags', ['node_id'], unique=False)
    op.create_index('ix_question_tags_question_id', 'question_tags', ['question_id'], unique=False)
    op.create_table('attempt_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('flag_for_review', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("source IN ('user', 'mcp')", name='ck_attempt_notes_source'),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attempt_notes_attempt_id', 'attempt_notes', ['attempt_id'], unique=False)
    op.create_index('ix_attempt_notes_flagged', 'attempt_notes', ['flag_for_review'], unique=False, postgresql_where='flag_for_review = true')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attempt_notes_flagged', table_name='attempt_notes', postgresql_where='flag_for_review = true')
    op.drop_index('ix_attempt_notes_attempt_id', table_name='attempt_notes')
    op.drop_table('attempt_notes')
    op.drop_index('ix_question_tags_question_id', table_name='question_tags')
    op.drop_index('ix_question_tags_node_id', table_name='question_tags')
    op.drop_table('question_tags')
    op.drop_table('question_features')
    op.drop_index('ix_attempts_uworld_test_id', table_name='attempts')
    op.drop_index('ix_attempts_question_id', table_name='attempts')
    op.drop_index('ix_attempts_question_attempted', table_name='attempts')
    op.drop_index('ix_attempts_attempted_at', table_name='attempts')
    op.drop_table('attempts')
    op.drop_index('ix_anki_note_tags_source', table_name='anki_note_tags')
    op.drop_index('ix_anki_note_tags_question_qid', table_name='anki_note_tags')
    op.drop_index('ix_anki_note_tags_node_id', table_name='anki_note_tags')
    op.drop_table('anki_note_tags')
    op.drop_index('ix_anki_card_reviews_card_reviewed', table_name='anki_card_reviews')
    op.drop_table('anki_card_reviews')
    op.drop_index('ix_questions_passage_id', table_name='questions')
    op.drop_index('ix_questions_needs_categorization', table_name='questions', postgresql_where=sa.text('needs_categorization = true'))
    op.drop_table('questions')
    op.drop_index('ix_outline_nodes_parent_id', table_name='outline_nodes')
    op.drop_index('ix_outline_nodes_course_id', table_name='outline_nodes')
    op.drop_table('outline_nodes')
    op.drop_index('ix_anki_writes_occurred_at', table_name='anki_writes')
    op.drop_table('anki_writes')
    op.drop_index('ix_anki_cards_due_date', table_name='anki_cards')
    op.drop_table('anki_cards')
    op.drop_index('ix_task_runs_job_started', table_name='task_runs')
    op.drop_index(op.f('ix_task_runs_job_name'), table_name='task_runs')
    op.drop_table('task_runs')
    # T27 fix: sa.Enum auto-creates the named TYPE on first CREATE TABLE
    # but DROP TABLE leaves it orphaned. Subsequent `upgrade head` after a
    # `downgrade base` would CREATE TYPE again → DuplicateObjectError.
    # Drop the type explicitly so the up→down→up roundtrip is clean.
    op.execute("DROP TYPE IF EXISTS task_run_status")
    op.drop_index('ix_raw_captures_qid_with_warnings', table_name='raw_captures', postgresql_where=sa.text('parse_warnings IS NOT NULL'))
    op.drop_index('ix_raw_captures_qid', table_name='raw_captures')
    op.drop_index('ix_raw_captures_captured_at', table_name='raw_captures')
    op.drop_table('raw_captures')
    op.drop_index('ix_passages_uworld_id', table_name='passages', postgresql_where=sa.text('uworld_passage_id IS NOT NULL'))
    op.drop_table('passages')
    op.drop_index('ix_media_undescribed', table_name='media', postgresql_where=sa.text('description IS NULL'))
    op.drop_table('media')
    op.drop_index('ix_llm_batch_runs_extractor_submitted', table_name='llm_batch_runs')
    op.drop_table('llm_batch_runs')
    op.drop_table('courses')
    op.drop_index('ix_anki_reviews_status_date', table_name='anki_reviews')
    op.drop_table('anki_reviews')
    op.drop_table('anki_notes')
    op.drop_table('anki_load_config')
    op.drop_index('ix_anki_assignments_status_scheduled', table_name='anki_assignments')
    op.drop_index('ix_anki_assignments_actual_unlock', table_name='anki_assignments')
    op.drop_table('anki_assignments')
    # ### end Alembic commands ###
