"""ticket 2.1 captures

Revision ID: 20260513_t21
Revises: 687869f1a03b
Create Date: 2026-05-13 22:38:13.457255

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "20260513_t21"
down_revision: Union[str, None] = "687869f1a03b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("local_path", sa.Text(), nullable=False),
        sa.Column("original_url", sa.Text(), nullable=True),
        sa.Column("mime_type", sa.Text(), nullable=False),
        sa.Column("width_px", sa.Integer(), nullable=True),
        sa.Column("height_px", sa.Integer(), nullable=True),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("description_model", sa.Text(), nullable=True),
        sa.Column("described_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_hash"),
    )
    op.create_index(
        "ix_media_undescribed",
        "media",
        ["id"],
        unique=False,
        postgresql_where=sa.text("description IS NULL"),
    )
    op.create_table(
        "passages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uworld_passage_id", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("html", sa.Text(), nullable=False),
        sa.Column("plain_text", sa.Text(), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_hash", name="uq_passages_content_hash"),
    )
    op.create_index(
        "ix_passages_uworld_id",
        "passages",
        ["uworld_passage_id"],
        unique=True,
        postgresql_where=sa.text("uworld_passage_id IS NOT NULL"),
    )
    op.create_table(
        "raw_captures",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.Text(), server_default="uworld", nullable=False),
        sa.Column("qid", sa.Text(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_html", sa.Text(), nullable=False),
        sa.Column("raw_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("parse_warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("extension_version", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("source IN ('uworld')", name="ck_raw_captures_source"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_raw_captures_captured_at", "raw_captures", ["captured_at"], unique=False)
    op.create_index("ix_raw_captures_qid", "raw_captures", ["qid"], unique=False)
    op.create_index(
        "ix_raw_captures_qid_with_warnings",
        "raw_captures",
        ["qid"],
        unique=False,
        postgresql_where=sa.text("parse_warnings IS NOT NULL"),
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("qid", sa.Text(), nullable=False),
        sa.Column("passage_id", sa.Integer(), nullable=True),
        sa.Column("stem_html", sa.Text(), nullable=False),
        sa.Column("stem_plain", sa.Text(), nullable=False),
        sa.Column("choices", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("correct_choice", sa.Text(), nullable=False),
        sa.Column("explanation_html", sa.Text(), nullable=True),
        sa.Column("explanation_plain", sa.Text(), nullable=True),
        sa.Column("uworld_aamc_tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("needs_categorization", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["passage_id"], ["passages.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("qid"),
    )
    op.create_index(
        "ix_questions_needs_categorization",
        "questions",
        ["id"],
        unique=False,
        postgresql_where=sa.text("needs_categorization = true"),
    )
    op.create_index("ix_questions_passage_id", "questions", ["passage_id"], unique=False)
    op.create_table(
        "attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("selected_choice", sa.Text(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("time_seconds", sa.Integer(), nullable=True),
        sa.Column("flagged", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_attempts_attempted_at", "attempts", ["attempted_at"], unique=False)
    op.create_index(
        "ix_attempts_question_attempted",
        "attempts",
        ["question_id", "attempted_at"],
        unique=False,
    )
    op.create_index("ix_attempts_question_id", "attempts", ["question_id"], unique=False)
    op.create_table(
        "question_tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=True),
        sa.Column("content_category_id", sa.Integer(), nullable=True),
        sa.Column("skill", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('uworld_map', 'llm', 'manual')", name="ck_question_tags_source"
        ),
        sa.CheckConstraint(
            "((topic_id IS NOT NULL)::int + (content_category_id IS NOT NULL)::int + (skill IS NOT NULL)::int) = 1",
            name="ck_question_tags_exactly_one_target",
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0.0 AND 1.0", name="ck_question_tags_confidence_range"
        ),
        sa.CheckConstraint(
            "skill IS NULL OR (skill BETWEEN 1 AND 4)",
            name="ck_question_tags_skill_range",
        ),
        sa.ForeignKeyConstraint(
            ["content_category_id"], ["content_categories.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "question_id",
            "topic_id",
            "content_category_id",
            "skill",
            "source",
            name="uq_question_tags_target_source",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        "ix_question_tags_content_category_id",
        "question_tags",
        ["content_category_id"],
        unique=False,
    )
    op.create_index("ix_question_tags_question_id", "question_tags", ["question_id"], unique=False)
    op.create_index("ix_question_tags_skill", "question_tags", ["skill"], unique=False)
    op.create_index("ix_question_tags_topic_id", "question_tags", ["topic_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_question_tags_topic_id", table_name="question_tags")
    op.drop_index("ix_question_tags_skill", table_name="question_tags")
    op.drop_index("ix_question_tags_question_id", table_name="question_tags")
    op.drop_index("ix_question_tags_content_category_id", table_name="question_tags")
    op.drop_table("question_tags")
    op.drop_index("ix_attempts_question_id", table_name="attempts")
    op.drop_index("ix_attempts_question_attempted", table_name="attempts")
    op.drop_index("ix_attempts_attempted_at", table_name="attempts")
    op.drop_table("attempts")
    op.drop_index("ix_questions_passage_id", table_name="questions")
    op.drop_index(
        "ix_questions_needs_categorization",
        table_name="questions",
        postgresql_where=sa.text("needs_categorization = true"),
    )
    op.drop_table("questions")
    op.drop_index(
        "ix_raw_captures_qid_with_warnings",
        table_name="raw_captures",
        postgresql_where=sa.text("parse_warnings IS NOT NULL"),
    )
    op.drop_index("ix_raw_captures_qid", table_name="raw_captures")
    op.drop_index("ix_raw_captures_captured_at", table_name="raw_captures")
    op.drop_table("raw_captures")
    op.drop_index(
        "ix_passages_uworld_id",
        table_name="passages",
        postgresql_where=sa.text("uworld_passage_id IS NOT NULL"),
    )
    op.drop_table("passages")
    op.drop_index(
        "ix_media_undescribed",
        table_name="media",
        postgresql_where=sa.text("description IS NULL"),
    )
    op.drop_table("media")
    # ### end Alembic commands ###
